# Generated by Django 5.1.6 on 2025-03-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userhighscore_alter_userforest_cells'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customisation_type', models.IntegerField()),
                ('colour_code', models.TextField()),
            ],
        ),
    ]
