# Generated by Django 5.1.6 on 2025-03-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customisations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customisations',
            old_name='colour_code',
            new_name='primary_colour_code',
        ),
        migrations.AddField(
            model_name='customisations',
            name='secondary_colour_code',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
