# Generated by Django 5.1.6 on 2025-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_colour_code_customisations_primary_colour_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforest',
            name='customisations',
            field=models.TextField(default='0,1,2'),
        ),
    ]
