name: CI/CD for Django on Railway

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 运行测试
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 部署到 Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # 安装 Railway CLI（如果未全局安装）
          npm install -g railway
          # 使用 Railway CLI 进行部署
          railway up
